"use client";

import { useState } from "react";

import AmountInput from "@/components/AmountInput";
import PeopleSelector from "@/components/PeopleSelector";
import PrimaryButton from "@/components/PrimaryButton";
import PromptPayCard from "@/components/PromptPayCard";
import QRDialog from "@/components/QRDialog";
import SplitSummary from "@/components/SplitSummary";

export default function Home() {
  const [openQR, setOpenQR] = useState(false);

  return (
    <>
      <main className="min-h-dvh overflow-hidden bg-[var(--page-background)] px-4 py-5 text-[var(--receipt-ink)] sm:px-6 sm:py-10">
        <div className="mx-auto flex w-full max-w-md flex-col items-center">
          <section className="receipt-paper animate-receipt-print w-full px-5 py-6 shadow-[0_24px_80px_rgb(51_33_20_/_0.18)] sm:px-7 sm:py-8">
            <header className="text-center">
              <p className="font-mono text-[0.68rem] uppercase tracking-[0.28em] text-[var(--receipt-muted)]">
                Restaurant Receipt
              </p>
              <h1 className="mt-2 text-4xl font-black leading-none tracking-normal">
                PayShare v2
              </h1>
              <p className="mt-2 font-mono text-xs uppercase tracking-[0.18em] text-[var(--receipt-muted)]">
                 Edition
              </p>
            </header>

            <div className="receipt-rule my-5" />

            <div className="space-y-4">
              <PromptPayCard />
              <AmountInput />
              <PeopleSelector />
              <SplitSummary />
            </div>

            <div className="receipt-rule my-5" />

            <section className="space-y-4">
              <div className="text-center font-mono text-[0.72rem] uppercase tracking-[0.22em] text-[var(--receipt-muted)]">
                QR section
              </div>
              <PrimaryButton onClick={() => setOpenQR(true)} />
            </section>

            <footer className="mt-6 text-center font-mono text-xs leading-6 text-[var(--receipt-muted)]">
              <p>Thank you </p>
              <p>Generated by 9M</p>
            </footer>
          </section>
        </div>
      </main>

      <QRDialog open={openQR} onOpenChange={setOpenQR} />
    </>
  );
}
